### ISSUE TITLE
absolute paths from build machine are packaged and used at runtime in some cases

### ISSUE THREAD

**Issue by solvingj** [codrsquad/portable-python#10]
I'm not sure how it is occurring, but people using the portable python interpreter that I built on my machine are getting my local paths printed out in stack traces:

```
/opt/portable_python/3.10.4/bin/python3 -m pip install --upgrade pip
Traceback (most recent call last):
  File "<stdin>", line 44, in <module>
  File "<stdin>", line 30, in main
FileNotFoundError: [Errno 2] No such file or directory: '/Users/myusername/_src/git_python/portable_python_builder/version_3_11_0/build/deps'
```

I did a quick search for the string and I found my local machine paths littered all over in:
`_sysconfigdata__darwin_darwin.py`

It's also in the `Makefile` which is packaged and bundled, but it seemed less likely to be getting used at runtime.

Would it be possible to add a step before creating the dist/...tar.gz files to perform a replace_all on whatever path is detected to be the root of the build directory?  Like in my case I ran `portable-python` command in `/Users/myusername/_src/git_python/portable_python_builder/version_3_11_0`, so replacing that string in both Makefile and the py file would sanitize them.

**Comment by solvingj** [comment]
Looks like they are embedded in binary files such as these two, and perhaps more:

```
./lib/python3.10/lib-dynload/_hashlib.cpython-310-darwin.so
./lib/python3.10/lib-dynload/_ssl.cpython-310-darwin.so
```

**Comment by zsimic** [comment]
I tried to reproduce but don't see this. How do you observe that `_hashlib` has references to the build path for example?
Also, usually the build folder used is intentionally called `./build/.../ppp-marker` (`ppp-marker` is relatively unique...).

Did you use `--prefix` somewhere in config?

**Comment by solvingj** [comment]
Sorry I should have posted more details as I found them.  
No I never used `--prefix`. 

So one way to demonstrate the SSL cert issue specifically is to run this command with the portable python:

`python -c "import ssl;print(ssl.get_default_verify_paths())"`

Here is an example of the output, regardless of what machine I run it on, the result is the same, the paths are the paths I built the binaries in:
```
DefaultVerifyPaths(
cafile=None, 
capath=None, openssl_cafile_env='SSL_CERT_FILE', 
openssl_cafile='/Users/myusername/_src/git_python/portable_python_builder/version_3_11_0/build/deps/cert.pem', 
openssl_capath_env='SSL_CERT_DIR', 
openssl_capath='/Users/myusername/_src/git_python/portable_python_builder/version_3_11_0/build/deps/certs'
)
```



Here's another good way to demonstrate the issue. 
Regarding the files I mentioned, just run the strings command on them:

`strings lib/python3.11/lib-dynload/_ssl.cpython-311-darwin.so | grep build/deps`

Example output
```
/Users/myusername/_src/git_python/portable_python_builder/version_3_11_0/build/deps/ct_log_list.cnf
OPENSSLDIR: "/Users/myusername/_src/git_python/portable_python_builder/version_3_11_0/build/deps"
ENGINESDIR: "/Users/myusername/_src/git_python/portable_python_builder/version_3_11_0/build/deps/lib/engines-1.1"
/Users/myusername/_src/git_python/portable_python_builder/version_3_11_0/build/deps/lib/engines-1.1
/Users/myusername/_src/git_python/portable_python_builder/version_3_11_0/build/deps/private
/Users/myusername/_src/git_python/portable_python_builder/version_3_11_0/build/deps
/Users/myusername/_src/git_python/portable_python_builder/version_3_11_0/build/deps/certs
/Users/myusername/_src/git_python/portable_python_builder/version_3_11_0/build/deps/cert.pem
```



And then again for hash lib:


`strings lib/python3.11/lib-dynload/_hashlib.cpython-311-darwin.so | grep build/deps`

```
/Users/myusername/_src/git_python/portable_python_builder/version_3_11_0/build/deps/ct_log_list.cnf
/Users/myusername/_src/git_python/portable_python_builder/version_3_11_0/build/deps/lib/engines-1.1
/Users/myusername/_src/git_python/portable_python_builder/version_3_11_0/build/deps/private
/Users/myusername/_src/git_python/portable_python_builder/version_3_11_0/build/deps
/Users/myusername/_src/git_python/portable_python_builder/version_3_11_0/build/deps/certs
/Users/myusername/_src/git_python/portable_python_builder/version_3_11_0/build/deps/cert.pem
```

**Comment by solvingj** [comment]
I should also add that changing any of this behavior seems very likely to require patching of build system files for openssl (a transitive dep of python), which seems like it will end up being brittle and unsupportable for this project, especially for something that may only be desired by a subset of users. I would completely understand that. 

With that said, it's pretty unfortunate that this very reasonable code simply won't work out of the box and there's literally no way to fix it in the .tar.gz files.  Currently the user has to take extra steps on the consuming machine to make it work. 

```
import urllib.request
url = 'https://www.python.org/ftp/python/3.10.10/python-3.10.10-macos11.pkg'
req = urllib.request.Request(url)
with urllib.request.urlopen(req) as response:
    the_page = response.read()
```

**Comment by solvingj** [comment]
Well now that I look back through the codebase and see this, it seems much more reasonable that you could expose openssl build flags to the caller through various means, I'll see if I can tweak it here and solve my cert problem in the meantime.
https://github.com/codrsquad/portable-python/blob/main/src/portable_python/external/xcpython.py#L151

**Comment by solvingj** [comment]
Here's the modern behavior from the changelog:

<blockquote>
To clarify their intended purposes, the Configure options
 --prefix and --openssldir change their semantics, and become more
 straightforward and less interdependent.

--prefix shall be used exclusively to give the location INSTALLTOP
 where programs, scripts, libraries, include files and manuals are
 going to be installed.  The default is now /usr/local.

 --openssldir shall be used exclusively to give the default
 location OPENSSLDIR where certificates, private keys, CRLs are
 managed.  This is also where the default openssl.cnf gets
 installed.
 If the directory given with this option is a relative path, the
 values of both the --prefix value and the --openssldir value will
 be combined to become OPENSSLDIR.
 The default for --openssldir is INSTALLTOP/ssl.

 Anyone who uses --openssldir to specify where OpenSSL is to be
 installed MUST change to use --prefix instead.
 [Richard Levitte]
</blockquote>

**Comment by solvingj** [comment]
Also of note, CPythons own workaround for this is here:

https://github.com/python/cpython/blob/main/Mac/BuildScript/resources/install_certificates.command

So the idea is that `python` bundles `pip` which requires `certifi` which also must be bundled, and which includes a `cacert.pem` file.  

So the script calls `ssl.get_default_verify_paths().openssl_cafile` to figure out where OpenSSL is looking for a certificate so it can put a symlink there.  That function effectively returns the value of `<PREFIX_DIR>/<OPENSSLDIR>/cacert.pem` from compile time. 

https://github.com/openssl/openssl/blob/master/include/internal/common.h#L64-L70

```
# ifndef OPENSSL_SYS_VMS
#  define X509_CERT_AREA          OPENSSLDIR
#  define X509_CERT_DIR           OPENSSLDIR "/certs"
#  define X509_CERT_FILE          OPENSSLDIR "/cert.pem"
#  define X509_PRIVATE_DIR        OPENSSLDIR "/private"
#  define CTLOG_FILE              OPENSSLDIR "/ct_log_list.cnf"
```

This is all an obvious problem for a project like this one (portable-python). 

Users will expect to be able to run the command and the build from any arbitrary directory (as I have), and for consumers to extract and run from any arbitrary directory.  Nobody would expect that the full path to the build directory structure needs to exist on the consumer machine... but that is the situation right now for the default certificate resolution of `urllib`, and all the other standard library modules that import `ssl`.

Really no easy workaround.  Kind of a bummer.

**Comment by zsimic** [comment]
Interesting! Lots to read, I'll check it out.
I can't reproduce right now. The build folder is usually `build/macos-arm64-3.11.2/ppp-marker`, I search for `ppp-marker` in my binary and can't find any trace of it (I used `ppp-marker` because I figured it'd be quite unique to search for, the "ppp" stands for "portable python path"

So, neither `strings`, nor a full-blown text search (I use [the_silver_searcher](https://github.com/ggreer/the_silver_searcher)) doesn't show any trace of `ppp-marker`

I'm curious to know how come you don't have a `ppp-marker` subfolder, and how/why it's not generating statically linked `.so`-s

**Comment by solvingj** [comment]
Just use the strings command on  _ssl.cpython-311-darwin.so and grep for OPENSSLDIR . What does that show.

**Comment by zsimic** [comment]
In my case, it shows `OPENSSLDIR ` is `/etc/ssl`
